//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstDbApp.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int GenderID { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public bool IsActive { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }

        public static explicit operator Employee(FirstDbApp.ViewModel.EmployeeVM employee)
        {
            Employee empdb = new Employee();
            empdb.EmployeeID = employee.EmployeeID;
            empdb.FirstName = employee.FirstName;
            empdb.LastName = employee.LastName;
            empdb.GenderID = employee.GenderID;
            empdb.IsActive = employee.IsActive;
            empdb.DepartmentID = employee.DepartmentID;
            empdb.Address = employee.Address;
            empdb.DateOfBirth = employee.DateOfBirth;
            empdb.DateOfJoining = employee.DateOfJoining;
            empdb.ContactNumber = employee.ContactNumber;
            empdb.Email = employee.Email;
            empdb.CreatedBy = employee.CreatedBy;
            empdb.CreatedDate = employee.CreatedDate;
            empdb.ModifiedBy = employee.ModifiedBy;
            empdb.ModifiedDate = employee.ModifiedDate;
            return empdb;
        }
    }
}
